// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using SysPescaderiaSaavedra.Web.Models;

#nullable disable

namespace SysPescaderiaSaavedra.Web.Migrations
{
    [DbContext(typeof(PescaderiaContext))]
    [Migration("20260226145600_InitialCreate")]
    partial class InitialCreate
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.11")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("SysPescaderiaSaavedra.Web.Models.Categoria", b =>
                {
                    b.Property<int>("CategoriaId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("categoria_id");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("CategoriaId"));

                    b.Property<bool>("Estado")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bit")
                        .HasDefaultValue(true)
                        .HasColumnName("estado");

                    b.Property<DateTime>("FechaRegistro")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime")
                        .HasColumnName("fecha_registro")
                        .HasDefaultValueSql("(getdate())");

                    b.Property<string>("Nombre")
                        .IsRequired()
                        .HasMaxLength(50)
                        .IsUnicode(false)
                        .HasColumnType("varchar(50)")
                        .HasColumnName("nombre");

                    b.HasKey("CategoriaId")
                        .HasName("PK__Categori__DB875A4FA143C463");

                    b.HasIndex(new[] { "Nombre" }, "UQ__Categori__72AFBCC6449EBDC1")
                        .IsUnique();

                    b.ToTable("Categorias");
                });

            modelBuilder.Entity("SysPescaderiaSaavedra.Web.Models.Cliente", b =>
                {
                    b.Property<int>("ClienteId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("cliente_id");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("ClienteId"));

                    b.Property<string>("Apellido")
                        .IsRequired()
                        .HasMaxLength(100)
                        .IsUnicode(false)
                        .HasColumnType("varchar(100)")
                        .HasColumnName("apellido");

                    b.Property<string>("Direccion")
                        .IsRequired()
                        .HasMaxLength(255)
                        .IsUnicode(false)
                        .HasColumnType("varchar(255)")
                        .HasColumnName("direccion");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasMaxLength(100)
                        .IsUnicode(false)
                        .HasColumnType("varchar(100)")
                        .HasColumnName("email");

                    b.Property<bool>("Estado")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bit")
                        .HasDefaultValue(true)
                        .HasColumnName("estado");

                    b.Property<DateTime>("FechaRegistro")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime")
                        .HasColumnName("fecha_registro")
                        .HasDefaultValueSql("(getdate())");

                    b.Property<string>("Identificacion")
                        .IsRequired()
                        .HasMaxLength(20)
                        .IsUnicode(false)
                        .HasColumnType("varchar(20)")
                        .HasColumnName("identificacion");

                    b.Property<string>("Nombre")
                        .IsRequired()
                        .HasMaxLength(100)
                        .IsUnicode(false)
                        .HasColumnType("varchar(100)")
                        .HasColumnName("nombre");

                    b.Property<string>("Telefono")
                        .IsRequired()
                        .HasMaxLength(20)
                        .IsUnicode(false)
                        .HasColumnType("varchar(20)")
                        .HasColumnName("telefono");

                    b.HasKey("ClienteId")
                        .HasName("PK__Clientes__47E34D64790CAAC5");

                    b.HasIndex(new[] { "Email" }, "UQ__Clientes__AB6E6164E918D209")
                        .IsUnique();

                    b.HasIndex(new[] { "Identificacion" }, "UQ__Clientes__C196DEC70B02F626")
                        .IsUnique();

                    b.ToTable("Clientes");
                });

            modelBuilder.Entity("SysPescaderiaSaavedra.Web.Models.DetalleVenta", b =>
                {
                    b.Property<int>("DetalleVentaId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("detalle_venta_id");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("DetalleVentaId"));

                    b.Property<decimal>("Cantidad")
                        .HasColumnType("decimal(10, 2)")
                        .HasColumnName("cantidad");

                    b.Property<decimal>("PrecioVentaUnitario")
                        .HasColumnType("decimal(10, 2)")
                        .HasColumnName("precio_venta_unitario");

                    b.Property<int>("ProductoId")
                        .HasColumnType("int")
                        .HasColumnName("producto_id");

                    b.Property<decimal>("Subtotal")
                        .HasColumnType("decimal(10, 2)")
                        .HasColumnName("subtotal");

                    b.Property<int>("VentaId")
                        .HasColumnType("int")
                        .HasColumnName("venta_id");

                    b.HasKey("DetalleVentaId")
                        .HasName("PK__Detalle___652699E323D89012");

                    b.HasIndex("ProductoId");

                    b.HasIndex("VentaId");

                    b.ToTable("Detalle_Venta", (string)null);
                });

            modelBuilder.Entity("SysPescaderiaSaavedra.Web.Models.IngresoMercaderia", b =>
                {
                    b.Property<int>("IngresoId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("ingreso_id");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("IngresoId"));

                    b.Property<DateTime>("FechaIngreso")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime")
                        .HasColumnName("fecha_ingreso")
                        .HasDefaultValueSql("(getdate())");

                    b.Property<int>("ProveedorId")
                        .HasColumnType("int")
                        .HasColumnName("proveedor_id");

                    b.Property<decimal>("TotalCompra")
                        .HasColumnType("decimal(10, 2)")
                        .HasColumnName("total_compra");

                    b.Property<int>("UsuarioId")
                        .HasColumnType("int")
                        .HasColumnName("usuario_id");

                    b.HasKey("IngresoId")
                        .HasName("PK__Ingreso___4E42CFD9027D0CC7");

                    b.HasIndex("ProveedorId");

                    b.HasIndex("UsuarioId");

                    b.ToTable("Ingreso_Mercaderia", (string)null);
                });

            modelBuilder.Entity("SysPescaderiaSaavedra.Web.Models.Lote", b =>
                {
                    b.Property<int>("LoteId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("lote_id");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("LoteId"));

                    b.Property<decimal>("CantidadInicial")
                        .HasColumnType("decimal(10, 2)")
                        .HasColumnName("cantidad_inicial");

                    b.Property<string>("CodigoLote")
                        .HasMaxLength(50)
                        .IsUnicode(false)
                        .HasColumnType("varchar(50)")
                        .HasColumnName("codigo_lote");

                    b.Property<decimal>("CostoUnitario")
                        .HasColumnType("decimal(10, 2)")
                        .HasColumnName("costo_unitario");

                    b.Property<bool>("Estado")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bit")
                        .HasDefaultValue(true)
                        .HasColumnName("estado");

                    b.Property<DateOnly?>("FechaProduccion")
                        .HasColumnType("date")
                        .HasColumnName("fecha_produccion");

                    b.Property<DateOnly>("FechaVencimiento")
                        .HasColumnType("date")
                        .HasColumnName("fecha_vencimiento");

                    b.Property<int>("IngresoId")
                        .HasColumnType("int")
                        .HasColumnName("ingreso_id");

                    b.Property<int>("ProductoId")
                        .HasColumnType("int")
                        .HasColumnName("producto_id");

                    b.Property<decimal>("StockActual")
                        .HasColumnType("decimal(10, 2)")
                        .HasColumnName("stock_actual");

                    b.HasKey("LoteId")
                        .HasName("PK__Lotes__E0E20FB3F37BC898");

                    b.HasIndex("IngresoId");

                    b.HasIndex("ProductoId");

                    b.ToTable("Lotes");
                });

            modelBuilder.Entity("SysPescaderiaSaavedra.Web.Models.Producto", b =>
                {
                    b.Property<int>("ProductoId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("producto_id");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("ProductoId"));

                    b.Property<int>("CategoriaId")
                        .HasColumnType("int")
                        .HasColumnName("categoria_id");

                    b.Property<string>("Descripcion")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("descripcion");

                    b.Property<bool>("Estado")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bit")
                        .HasDefaultValue(true)
                        .HasColumnName("estado");

                    b.Property<DateTime>("FechaRegistro")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime")
                        .HasColumnName("fecha_registro")
                        .HasDefaultValueSql("(getdate())");

                    b.Property<string>("Nombre")
                        .IsRequired()
                        .HasMaxLength(100)
                        .IsUnicode(false)
                        .HasColumnType("varchar(100)")
                        .HasColumnName("nombre");

                    b.Property<decimal>("PrecioVenta")
                        .HasColumnType("decimal(10, 2)")
                        .HasColumnName("precio_venta");

                    b.Property<bool>("PublicadoWeb")
                        .HasColumnType("bit")
                        .HasColumnName("publicado_web");

                    b.Property<decimal>("StockGlobal")
                        .HasColumnType("decimal(10, 2)")
                        .HasColumnName("stock_global");

                    b.Property<string>("UnidadMedida")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasMaxLength(20)
                        .IsUnicode(false)
                        .HasColumnType("varchar(20)")
                        .HasDefaultValue("kg")
                        .HasColumnName("unidad_medida");

                    b.HasKey("ProductoId")
                        .HasName("PK__Producto__FB5CEEECBA6DD7ED");

                    b.HasIndex("CategoriaId");

                    b.ToTable("Productos");
                });

            modelBuilder.Entity("SysPescaderiaSaavedra.Web.Models.Proveedores", b =>
                {
                    b.Property<int>("ProveedorId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("proveedor_id");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("ProveedorId"));

                    b.Property<string>("Contacto")
                        .IsRequired()
                        .HasMaxLength(100)
                        .IsUnicode(false)
                        .HasColumnType("varchar(100)")
                        .HasColumnName("contacto");

                    b.Property<string>("Direccion")
                        .IsRequired()
                        .HasMaxLength(255)
                        .IsUnicode(false)
                        .HasColumnType("varchar(255)")
                        .HasColumnName("direccion");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasMaxLength(100)
                        .IsUnicode(false)
                        .HasColumnType("varchar(100)")
                        .HasColumnName("email");

                    b.Property<bool>("Estado")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bit")
                        .HasDefaultValue(true)
                        .HasColumnName("estado");

                    b.Property<DateTime>("FechaRegistro")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime")
                        .HasColumnName("fecha_registro")
                        .HasDefaultValueSql("(getdate())");

                    b.Property<string>("Nit")
                        .IsRequired()
                        .HasMaxLength(20)
                        .IsUnicode(false)
                        .HasColumnType("varchar(20)")
                        .HasColumnName("nit");

                    b.Property<string>("NombreEmpresa")
                        .IsRequired()
                        .HasMaxLength(100)
                        .IsUnicode(false)
                        .HasColumnType("varchar(100)")
                        .HasColumnName("nombre_empresa");

                    b.Property<string>("Telefono")
                        .IsRequired()
                        .HasMaxLength(20)
                        .IsUnicode(false)
                        .HasColumnType("varchar(20)")
                        .HasColumnName("telefono");

                    b.HasKey("ProveedorId")
                        .HasName("PK__Proveedo__88BBADA49BA4A831");

                    b.HasIndex(new[] { "Email" }, "UQ__Proveedo__AB6E616474F21045")
                        .IsUnique();

                    b.HasIndex(new[] { "Nit" }, "UQ__Proveedo__DF97D0E42AAA13B8")
                        .IsUnique();

                    b.ToTable("Proveedores");
                });

            modelBuilder.Entity("SysPescaderiaSaavedra.Web.Models.Roles", b =>
                {
                    b.Property<int>("RolId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("rol_id");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("RolId"));

                    b.Property<string>("Descripcion")
                        .IsRequired()
                        .HasMaxLength(255)
                        .IsUnicode(false)
                        .HasColumnType("varchar(255)")
                        .HasColumnName("descripcion");

                    b.Property<bool>("Estado")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bit")
                        .HasDefaultValue(true)
                        .HasColumnName("estado");

                    b.Property<DateTime>("FechaRegistro")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime")
                        .HasColumnName("fecha_registro")
                        .HasDefaultValueSql("(getdate())");

                    b.Property<string>("Nombre")
                        .IsRequired()
                        .HasMaxLength(50)
                        .IsUnicode(false)
                        .HasColumnType("varchar(50)")
                        .HasColumnName("nombre");

                    b.HasKey("RolId")
                        .HasName("PK__Roles__CF32E4435D492887");

                    b.HasIndex(new[] { "Nombre" }, "UQ__Roles__72AFBCC661415CBB")
                        .IsUnique();

                    b.ToTable("Roles");
                });

            modelBuilder.Entity("SysPescaderiaSaavedra.Web.Models.Usuario", b =>
                {
                    b.Property<int>("UsuarioId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("usuario_id");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("UsuarioId"));

                    b.Property<string>("ClaveHash")
                        .IsRequired()
                        .HasMaxLength(255)
                        .IsUnicode(false)
                        .HasColumnType("varchar(255)")
                        .HasColumnName("clave_hash");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasMaxLength(100)
                        .IsUnicode(false)
                        .HasColumnType("varchar(100)")
                        .HasColumnName("email");

                    b.Property<bool>("Estado")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bit")
                        .HasDefaultValue(true)
                        .HasColumnName("estado");

                    b.Property<DateTime>("FechaRegistro")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime")
                        .HasColumnName("fecha_registro")
                        .HasDefaultValueSql("(getdate())");

                    b.Property<string>("NombreCompleto")
                        .IsRequired()
                        .HasMaxLength(150)
                        .IsUnicode(false)
                        .HasColumnType("varchar(150)")
                        .HasColumnName("nombre_completo");

                    b.Property<string>("NombreUsuario")
                        .IsRequired()
                        .HasMaxLength(50)
                        .IsUnicode(false)
                        .HasColumnType("varchar(50)")
                        .HasColumnName("nombre_usuario");

                    b.Property<int>("RolId")
                        .HasColumnType("int")
                        .HasColumnName("rol_id");

                    b.HasKey("UsuarioId")
                        .HasName("PK__Usuarios__2ED7D2AF796838DD");

                    b.HasIndex("RolId");

                    b.HasIndex(new[] { "Email" }, "UQ__Usuarios__AB6E6164BA632CFF")
                        .IsUnique();

                    b.HasIndex(new[] { "NombreUsuario" }, "UQ__Usuarios__D4D22D74B609B67F")
                        .IsUnique();

                    b.ToTable("Usuarios");
                });

            modelBuilder.Entity("SysPescaderiaSaavedra.Web.Models.Venta", b =>
                {
                    b.Property<int>("VentaId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("venta_id");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("VentaId"));

                    b.Property<int>("ClienteId")
                        .HasColumnType("int")
                        .HasColumnName("cliente_id");

                    b.Property<bool>("Estado")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bit")
                        .HasDefaultValue(true)
                        .HasColumnName("estado");

                    b.Property<DateTime>("FechaVenta")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime")
                        .HasColumnName("fecha_venta")
                        .HasDefaultValueSql("(getdate())");

                    b.Property<decimal>("Impuesto")
                        .HasColumnType("decimal(10, 2)")
                        .HasColumnName("impuesto");

                    b.Property<decimal>("Subtotal")
                        .HasColumnType("decimal(10, 2)")
                        .HasColumnName("subtotal");

                    b.Property<decimal>("Total")
                        .HasColumnType("decimal(10, 2)")
                        .HasColumnName("total");

                    b.Property<int>("UsuarioId")
                        .HasColumnType("int")
                        .HasColumnName("usuario_id");

                    b.HasKey("VentaId")
                        .HasName("PK__Ventas__B1350809C61DF778");

                    b.HasIndex("ClienteId");

                    b.HasIndex("UsuarioId");

                    b.ToTable("Ventas");
                });

            modelBuilder.Entity("SysPescaderiaSaavedra.Web.Models.DetalleVenta", b =>
                {
                    b.HasOne("SysPescaderiaSaavedra.Web.Models.Producto", "Producto")
                        .WithMany("DetalleVenta")
                        .HasForeignKey("ProductoId")
                        .IsRequired()
                        .HasConstraintName("FK__Detalle_V__produ__6C190EBB");

                    b.HasOne("SysPescaderiaSaavedra.Web.Models.Venta", "Venta")
                        .WithMany("DetalleVenta")
                        .HasForeignKey("VentaId")
                        .IsRequired()
                        .HasConstraintName("FK__Detalle_V__venta__6B24EA82");

                    b.Navigation("Producto");

                    b.Navigation("Venta");
                });

            modelBuilder.Entity("SysPescaderiaSaavedra.Web.Models.IngresoMercaderia", b =>
                {
                    b.HasOne("SysPescaderiaSaavedra.Web.Models.Proveedores", "Proveedor")
                        .WithMany("IngresoMercaderia")
                        .HasForeignKey("ProveedorId")
                        .IsRequired()
                        .HasConstraintName("FK__Ingreso_M__prove__5BE2A6F2");

                    b.HasOne("SysPescaderiaSaavedra.Web.Models.Usuario", "Usuario")
                        .WithMany("IngresoMercaderia")
                        .HasForeignKey("UsuarioId")
                        .IsRequired()
                        .HasConstraintName("FK__Ingreso_M__usuar__5CD6CB2B");

                    b.Navigation("Proveedor");

                    b.Navigation("Usuario");
                });

            modelBuilder.Entity("SysPescaderiaSaavedra.Web.Models.Lote", b =>
                {
                    b.HasOne("SysPescaderiaSaavedra.Web.Models.IngresoMercaderia", "Ingreso")
                        .WithMany("Lotes")
                        .HasForeignKey("IngresoId")
                        .IsRequired()
                        .HasConstraintName("FK__Lotes__ingreso_i__60A75C0F");

                    b.HasOne("SysPescaderiaSaavedra.Web.Models.Producto", "Producto")
                        .WithMany("Lotes")
                        .HasForeignKey("ProductoId")
                        .IsRequired()
                        .HasConstraintName("FK__Lotes__producto___619B8048");

                    b.Navigation("Ingreso");

                    b.Navigation("Producto");
                });

            modelBuilder.Entity("SysPescaderiaSaavedra.Web.Models.Producto", b =>
                {
                    b.HasOne("SysPescaderiaSaavedra.Web.Models.Categoria", "Categoria")
                        .WithMany("Productos")
                        .HasForeignKey("CategoriaId")
                        .IsRequired()
                        .HasConstraintName("FK__Productos__categ__5812160E");

                    b.Navigation("Categoria");
                });

            modelBuilder.Entity("SysPescaderiaSaavedra.Web.Models.Usuario", b =>
                {
                    b.HasOne("SysPescaderiaSaavedra.Web.Models.Roles", "Rol")
                        .WithMany("Usuarios")
                        .HasForeignKey("RolId")
                        .IsRequired()
                        .HasConstraintName("FK__Usuarios__rol_id__44FF419A");

                    b.Navigation("Rol");
                });

            modelBuilder.Entity("SysPescaderiaSaavedra.Web.Models.Venta", b =>
                {
                    b.HasOne("SysPescaderiaSaavedra.Web.Models.Cliente", "Cliente")
                        .WithMany("Venta")
                        .HasForeignKey("ClienteId")
                        .IsRequired()
                        .HasConstraintName("FK__Ventas__cliente___6754599E");

                    b.HasOne("SysPescaderiaSaavedra.Web.Models.Usuario", "Usuario")
                        .WithMany("Venta")
                        .HasForeignKey("UsuarioId")
                        .IsRequired()
                        .HasConstraintName("FK__Ventas__usuario___68487DD7");

                    b.Navigation("Cliente");

                    b.Navigation("Usuario");
                });

            modelBuilder.Entity("SysPescaderiaSaavedra.Web.Models.Categoria", b =>
                {
                    b.Navigation("Productos");
                });

            modelBuilder.Entity("SysPescaderiaSaavedra.Web.Models.Cliente", b =>
                {
                    b.Navigation("Venta");
                });

            modelBuilder.Entity("SysPescaderiaSaavedra.Web.Models.IngresoMercaderia", b =>
                {
                    b.Navigation("Lotes");
                });

            modelBuilder.Entity("SysPescaderiaSaavedra.Web.Models.Producto", b =>
                {
                    b.Navigation("DetalleVenta");

                    b.Navigation("Lotes");
                });

            modelBuilder.Entity("SysPescaderiaSaavedra.Web.Models.Proveedores", b =>
                {
                    b.Navigation("IngresoMercaderia");
                });

            modelBuilder.Entity("SysPescaderiaSaavedra.Web.Models.Roles", b =>
                {
                    b.Navigation("Usuarios");
                });

            modelBuilder.Entity("SysPescaderiaSaavedra.Web.Models.Usuario", b =>
                {
                    b.Navigation("IngresoMercaderia");

                    b.Navigation("Venta");
                });

            modelBuilder.Entity("SysPescaderiaSaavedra.Web.Models.Venta", b =>
                {
                    b.Navigation("DetalleVenta");
                });
#pragma warning restore 612, 618
        }
    }
}
